name: 'Composer PHP versions in range'
description: 'Get PHP versions in range from composer.json'
branding:
  icon: 'maximize'
  color: 'green'
inputs:
  upcomingReleases:
    description: 'Include upcoming new major or minor releases'
    required: false
  nightly:
    description: 'Include nightly of the next new major or minor releases'
    required: false
  workingDirectory:
    description: The directory to run this action in
    default: ""
    required: false
outputs:
  highest:
    description: 'The highest version found in range'
  lowest:
    description: 'The lowest version found in range'
  version:
    description: 'The versions found in range'
  upcoming:
    description: 'The upcoming version found in range, if any'
  nightly:
    description: 'The nightly version found in range, if any'
  extensions:
    description: 'The PHP extensions found in require and require-dev'
  requiredExtensions:
    description: 'The PHP extensions found in require only'
  requiredDevExtensions:
    description: 'The PHP extensions found in require-dev only'
runs:
  using: 'node16'
  main: 'main.js'
