name: 'Composer PHP versions in range'
description: 'Get '
branding:
  icon: 'maximize'
  color: 'green'
outputs:
  version:
    description: 'The versions found in range'
runs:
  using: 'node12'
  main: 'main.js'
